CREATE DATABASE IF NOT EXISTS walkly_db;

USE walkly_db;

CREATE TABLE IF NOT EXISTS users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(75) NOT NULL,
	email VARCHAR(150) NOT NULL,
	password VARCHAR(255) NOT NULL,
	joined_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	categories_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS business_users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	company_name VARCHAR(100) NOT NULL,
	category_id INT FOREIGN KEY REFERENCES categories(id) NOT NULL,	
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(75) NOT NULL,
	phone_number INT(20) NOT NULL,
	description VARCHAR(300),
	email VARCHAR(150) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS addresses(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	company_name VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	street_name VARCHAR(100) NOT NULL,
	post_code INT(10) NOT NULL,
	built_number INT(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS offers(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	description VARCHAR(255) NOT NULL,
	points INT NOT NULL
);

CREATE TABLE IF NOT EXISTS points(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	points INT NOT NULL
);

