CREATE DATABASE IF NOT EXISTS walkly_db;

USE walkly_db;

CREATE TABLE IF NOT EXISTS users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(75) NOT NULL,
	email VARCHAR(150) NOT NULL,
	password VARCHAR(255) NOT NULL,
	joined_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	categories_name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS business_users(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	company_name VARCHAR(100) NOT NULL,
	category_id INT FOREIGN KEY REFERENCES categories(id) NOT NULL,	
	business_hours INT NOT NULL,
	offers INT FOREIGN KEY REFERENCES offers(id),
	first_name VARCHAR(50) NOT NULL,
	last_name VARCHAR(75) NOT NULL,
	phone_number VARCHAR(20) NOT NULL,
	description VARCHAR(300),
	email VARCHAR(150) NOT NULL,
	password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS addresses(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	company_id INT FOREIGN KEY REFERENCES business_users(id) NOT NULL,
	city VARCHAR(100) NOT NULL,
	street_name VARCHAR(100) NOT NULL,
	post_code VARCHAR(10) NOT NULL,
	built_number INT(5) NOT NULL, 
);

CREATE TABLE IF NOT EXISTS offers(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	date_from_to VARCHAR(30),
	coupon_count INT,
	business_user_id INT,
	description VARCHAR(255) NOT NULL,
	points INT NOT NULL
);

CREATE TABLE IF NOT EXISTS points(
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INT FOREIGN KEY REFERENCES users(id)
	points INT NOT NULL
);
CREATE TABLE IF NOT EXISTS active_sessions (
	id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	user_id INT NOT NULL,
	cookie VARCHAR(20) NOT NULL
);

